# Generated by Django 4.2.4 on 2023-08-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('byimage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='logo_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='nationality',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NationalityPlayer', to='byimage.nationality'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PositionPlayer', to='byimage.position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TeamPlayer', to='byimage.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LeagueTeam', to='byimage.league'),
        ),
    ]
